#!/bin/sh
mkdir -p /home/pnjoku/webapps/blog_app/run
pid=$(/sbin/pidof /home/pnjoku/webapps/blog_app/bin/node)
if echo "$pid" | grep -q " "; then
  pid=""
fi
if [ -n "$pid" ]; then
  user=$(ps -p $pid -o user | tail -n 1)
  if [ $user = "pnjoku" ]; then
    exit 0
  fi
fi
nohup /home/pnjoku/webapps/blog_app/bin/node /home/pnjoku/webapps/blog_app/blog/app.js > /dev/null 2>&1 &
/sbin/pidof /home/pnjoku/webapps/blog_app/bin/node > /home/pnjoku/webapps/blog_app/run/node.pid
